### ISSUE TITLE
当数组中只有一个view，数组布局会失效，有什么方法解决吗？

### ISSUE THREAD

**Issue by GaoGuohao** [spicyShrimp/SnapKitExtension#1]
当数组中只有一个view，数组布局会失效，有什么方法解决吗？
我看代码里如果数组只有一个元素，直接return了？

**Comment by spicyShrimp** [comment]
你是布局什么界面?数组只有一个元素,直接布局就可以了.或者你也可以修改原方法,之前没有考虑这个

**Comment by uclort** [comment]
@spicyShrimp 比如动态布局，可能会有一个的情况，修改原方法，添加了 bottom 的约束但是不生效，不知道怎么修改了。

**Comment by GaoGuohao** [comment]
> 你是布局什么界面?数组只有一个元素,直接布局就可以了.或者你也可以修改原方法,之前没有考虑这个

ok，已经通过修改原方法兼容，单独判断了一下元素数量为1的情况。
